### ISSUE TITLE
Hotkeys not working after adding objects to action bar

### ISSUE THREAD

**Issue by fdc23** [opentibiabr/otclient#226]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Add an object to action bar.
2. Use any hotkey from f1 to f2 it won't work.

This issue is very similar to https://github.com/mehah/otclient/issues/183

At game_actionbar.lua after line 357
`closeObjectAssignWindow()`

To solve it. have to add
`modules.game_hotkeys.enableHotkeys(true)`

To enable hotkeys when the ObjectAssignWindow is closed.
Regards!

**Comment by Znote** [comment]
I believe this is a 1.4.2 bug that has been fixed. 1.4.2 release tag is getting a bit old, have you tried latest main commit?

**Comment by fdc23** [comment]
> I believe this is a 1.4.2 bug that has been fixed. 1.4.2 release tag is getting a bit old, have you tried latest main commit?

Yeah I have everything up-to-date. This solution worked for me, pheraps, it's because i'm using 8.6 enviroment. Regards!

**Comment by oarsc** [comment]
The problem was that when opening the assignObject weapon, `modules.game_hotkeys.enableHotkeys(false)` was being called twice, so you'll need to call `enableHotkeys(true)` twice too.

Some times multiple windows can stack, and it should be managed correctly.

I fixed the first error, not disabling the hotkeys twice. (hope it doesn't break anything else)

Thanks!
