### ISSUE TITLE
Missing catalog-content.json

### ISSUE THREAD

**Issue by Slipehr** [opentibiabr/otclient#290]
### Priority

Missing Content

### Area

- [X] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

I have built the OT client from latest master, and put the require .dat and .spr file, however since 12.81 (ref: https://github.com/mehah/otclient/commit/703b2f663e35785f6dd4a6dc62b195bdb3981c15 ) there is a change which also requires a catalog-content.json file to be in this folder.

Trying to run it towards TFS with 12.87 support
This seems to be missing.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nekiro** [comment]
There was always catalog-content.json, since tibia 11 came out.

Spr and dat is not supported for tibia 12, how would it be? Protocol 12 doesn't use old spr/dat files, if you want to use dat and spr with tibia 12, then you most likely need to use spr/dat with latest sprites, it's available on otland and use 1098.
I can make it load tibia dat/spr from 1098, but other than that there is nothing more that I can do to support old files with newer protocol.
Dat/spr was dropped by cipsoft after tibia 11 (now 12) came out.
