### ISSUE TITLE
Drawing Problem

### ISSUE THREAD

**Issue by Klonoa88** [opentibiabr/otclient#300]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

After commit **Drawpool v2 RC**, floors, walls, shaders and others draws strange. This did not happen before.

**Ground Now:**
[Image](https://i.imgur.com/W5EAJdv.png)

**Ground Before:**
[Image](https://i.imgur.com/DiMp5pH.png)

**Shader Now:**
[Image](https://www.dropbox.com/s/esc31wl5knm1f93/Testing_wRRALHSNZ1.mp4?dl=0)

**Shader Before:**
[Image](https://www.dropbox.com/s/nwqh9uc53u9uyri/Start_4uXFytzA6k.mp4?dl=0)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
you are testing with the clean project, without modifications and last revision, because here everything is normal.

![image](https://user-images.githubusercontent.com/2267386/178615451-59cd8ed2-004f-4ad3-acd1-375da4cda1e1.png)
![image](https://user-images.githubusercontent.com/2267386/178615518-852afb2d-dcd0-45d1-a0ca-a4454141ce15.png)

**Comment by Klonoa88** [comment]
Well I may have missed something. Which function should I look at to see if I can solve the problem?

**Comment by mehah** [comment]
you probably forgot about the flush.
https://github.com/mehah/otclient/blob/0237e616fbc6c5f209b3a121ddbfd1f208505132/src/client/mapview.cpp#L210

this will fix one of the problems.

**Comment by Klonoa88** [comment]
No. It's there :(
[Link](https://i.imgur.com/WPAYHxh.png)

**Comment by mehah** [comment]
it looks like it's not updating the floor identifier and who controls this is the "flush" method.

I nominate you to pass all your modifications to drawpool2 and not the other way around.

**Comment by Klonoa88** [comment]
Okej. I have compared almost all files between your sources and mine now and it looks the same (except my own modifications). Can't find what is wrong :(

**Comment by mehah** [comment]
I don't have access to your source code, so it's hard to help you, what you can do is get a clean base and apply your changes little by little and see where this problem occurs.

**Comment by Klonoa88** [comment]
Okay :)

**Comment by Klonoa88** [comment]
Okay now I've done as you said. I have one problem left. The floors between **0-7** draw strangely. This does not happen underground. It is as if the roof goes down one floor below and sometimes you see floors below through each other, for example if I am on floor **5**, I see floors **6** and **7** through. 

In this [Image](https://i.imgur.com/TgYam9z.jpeg) i am on floor **7** and the roof **(from floor 5)** has fallen down.

In this [Video](https://www.dropbox.com/s/tcaa5vk3h4gra8b/Release_4pUgTvZwjW.mp4?dl=0) i am in floor **7** and see floor **8**.

This happened somewhere in these 3 commits **(Drawpool v2 RC)**
[Image](https://i.imgur.com/Ozl2TX1.png)

**Comment by mehah** [comment]
@Klonoa88
I told you to test with your modifications and not with mine, because the client with the last commit, everything is in compliance.

![image](https://user-images.githubusercontent.com/2267386/179010164-c6448e64-e36f-4cc4-89e7-d2b315165016.png)
I just tested it with the client in the last revision on a map from my old server.

I will give you some points:

1- did you test with the clean client?
2- did you check in which modification you made that this problem started to occur?
3- About ARR_MAX_Z, this is the maximum amount of index based on your MAX_Z

the problem you pointed out happens when you don't execute the flush() method, because the flush() method that flushes all the references of the drawings that were grouped, if you look at the method

https://github.com/mehah/otclient/blob/8a03fce21e411e71ad065264775ee64ddb743476/src/framework/graphics/pool.h#L183

you will see that it clears the references of the grouped objects and jumps to the next index, if this release is not done, it will merge with the drawings below.

**Comment by Klonoa88** [comment]
The only custom modification I have is that I removed the black between floors 7-8, so that I see all floors between 0-15. Could that be the problem?

**Comment by mehah** [comment]
maybe, I need to see how your code is, to see if you're flushing correctly.

or try changing the MAX_ARR_Z to MAX_Z + 1

https://github.com/mehah/otclient/blob/8a03fce21e411e71ad065264775ee64ddb743476/src/framework/graphics/pool.h#L148
for
``` c++
     static constexpr uint8_t ARR_MAX_Z = MAX_Z + 1;
```

**Comment by Klonoa88** [comment]
static constexpr uint8_t ARR_MAX_Z = MAX_Z + 1;

Yep this seemed to do the trick: D
Thanks :)

**Comment by SkullzOTS** [comment]
> The only custom modification I have is that I removed the black between floors 7-8, so that I see all floors between 0-15. Could that be the problem?

how did you do it?
