### ISSUE TITLE
Stuttering while changing outfits with script while condition which prevent walking is applayed

### ISSUE THREAD

**Issue by bulawow** [opentibiabr/otclient#32]
Both gif examples using the same script on different clients 

I noticed that its happening when i try to spam arrow key's to move while having condition that prevents from walking (stun).

### Expected behaviour
Using edubart otclient
https://i.gyazo.com/4e2a0cd46f68ec028dd036da56188b79.mp4

### Actual behaviour
Using otclient 1.0
https://i.gyazo.com/ed09393bb1eedc985737b9fac873a3b9.mp4

**Comment by mehah** [comment]
sorry, but i will not support custom projects, my job is only on Tibia, if you want an engine for creating 2D MMORPG games, I suggest using Canary.

https://canary-platform.com/

But not to let you down, check this line, it is possible that the problem is there.

https://github.com/mehah/otclient/blob/8d53dc2c1df682933e665185a46009158a9b86b3/src/client/localplayer.cpp#L68

https://github.com/mehah/otclient/blob/8d53dc2c1df682933e665185a46009158a9b86b3/src/client/creature.h#L131

**Comment by bulawow** [comment]
also i did check something else, this time i was not using the stun condition but during that animation i was trying to step into house that player was not owning it and while it was pushing me back the stuttering happening too

**Comment by mehah** [comment]
> also i did check something else, this time i was not using the stun condition but during that animation i was trying to step into house that player was not owning it and while it was pushing me back the stuttering happening too

strange, do the test with the client without modifications and with vsync enabled and check if the mentioned problem occurs.

**Comment by bulawow** [comment]
Alright did it and results are the same as above
Also tried with and without vsync
