### ISSUE TITLE
Protocol 12.72

### ISSUE THREAD

**Issue by Fanghis** [opentibiabr/otclient#333]
### Priority

Missing Content

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What is missing?

Protocol 12.72 Otclient

Upgrade protocols is good, anyway older's also.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nekiro** [comment]
Looks like a deprecated issue, there is support for 12.91 atm

**Comment by Fanghis** [comment]
There is a support 12.91, but maybe anyone wants play 12.72 ? Atm is there 80% 8.6-10.98 servers, not everyone wants 12.91, we wish 12.64-12.72, but i understand i will find someone who can do It.

**Comment by nekiro** [comment]
Yeah, the protocol supported are 12.85-12.92, if you can deliver protocol structure for 12.72, then we can probably implement support for it. I'll reopen, because I didn't understand the issue properly. I didn't think of "backwards compatibility".
Problem with implementing old protocol versions is that it's hard to find exact structure for them.

**Comment by mehah** [comment]
well, I don't think anyone will waste time mapping packets to support 1272, so I'll close this issue.

**Comment by Alexv45** [comment]
yes no one will waste time with this. it's a shame, the servers go too fast in protocol and still they all have the same problems, bugs quests dungeons not finished since Protocol 9.1, now i understand tfs is 10.98 and not older.

**Comment by Alexv45** [comment]
It is 12.72 or / 12.72/11 you are looking for @Fanghis ?
There is a server doing this two protocols working with otc.
