### ISSUE TITLE
Draw flickering

### ISSUE THREAD

**Issue by mrianura** [opentibiabr/otclient#356]
### Priority

High

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Trees/mountains are flickering:
Using latest client (7edbe67cd8c2e1da024f74a850da53cbde117ae8) with pure 8.6 server.

[A bug happened!](https://gyazo.com/459672f3305920bd57fc4cc65c13e3b9)

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mehah** [comment]
are you in debug mode? These flickers occur when the optimization system is triggered, because when the CPU processing is too long, it groups the images and these flickers end up occurring, but this only happens if you are in debugmode, in which there are no optimizations and the processing it ends up being time consuming and he understands that he needs to try to optimize.

**Comment by mrianura** [comment]
yes i was using debug version
