### ISSUE TITLE
Bug when logging in GM/Player character ghost mode - TFS 1.5 7.72... Wing, aura.....

### ISSUE THREAD

**Issue by regizfilho** [opentibiabr/otclient#879]
### Priority

Low

### Area

- [ ] Data
- [X] Source
- [ ] Docker
- [ ] Other

### What happened?

Hey guys, I deployed wings, auras, shaders in TFS 1.5 clean on version 7.72, and every time I log in as a regular player in GM, it goes into Ghost mode.  I've revisited the deployment several times to see if I forgot something, but it seems to be ok. But I can't figure out why this ghost bug is happening.

Here's the example video.

[https://youtu.be/QjlWFJLcAOU](https://youtu.be/QjlWFJLcAOU)

I used this commit -> [feat: GameWingsAurasEffects connection server by kokekanon · Pull Request #1 · kokekanon/TFS-1.4.2-Compatible-Aura-Effect-Wings-Shader-MEHAH (https://github.com/kokekanon/TFS-1.4.2-Compatible-Aura-Effect-Wings-Shader-MEHAH/pull/1/files)](https://github.com/kokekanon/TFS-1.4.2-Compatible-Aura-Effect-Wings-Shader-MEHAH/pull/1/files)

### What OS are you seeing the problem on?

Linux, Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kokekanon** [comment]
# in a CLEAN distribution of 1.5 | 7.72 by nekiro
**the error is not reproducible.**
**NOT caused by AttachEffect commits**
I took the time to compile the clean distribution of nekiro 1.5 protocol 7.72.

https://github.com/kokekanon/TFS-1.5-7.72-Attach-Effect/commit/4841fbc7aef5828b14b4907c7cdce58246671da9

https://github.com/user-attachments/assets/8755c764-f1d2-4dc3-975c-1ba06815cca8

dll+ exe 
[1.5release772.zip](https://github.com/user-attachments/files/17029429/1.5release772.zip)

**Comment by regizfilho** [comment]
Hahaha I swear I've been looking for 3 days!! I'll revisit the code, thanks!

**Comment by regizfilho** [comment]
> # in a CLEAN distribution of 1.5 | 7.72 by nekiro
> **the error is not reproducible.** **NOT caused by AttachEffect commits** I took the time to compile the clean distribution of nekiro 1.5 protocol 7.72.
> 
> [kokekanon/TFS-1.5-7.72-Attach-Effect@4841fbc](https://github.com/kokekanon/TFS-1.5-7.72-Attach-Effect/commit/4841fbc7aef5828b14b4907c7cdce58246671da9)
> 
>  bandicam.2024-09-17.10-28-47-732.mp4 
> dll+ exe [1.5release772.zip](https://github.com/user-attachments/files/17029429/1.5release772.zip)

Did you use only these features? Only the ones below?
`
g_game.enableFeature(GameWingsAurasEffectsShader)
g_game.enableFeature(GameFormatCreatureName)
g_game.enableFeature(GameCreatureShader)
g_game.enableFeature(GameCreatureAttachedEffect)
g_game.enableFeature(GameItemShader)`

Does it work on linux? that's the system I'm playing with!

**Comment by regizfilho** [comment]
![image](https://github.com/user-attachments/assets/fd79fe7c-de79-4a76-89b9-8d2ac9c17b4b)

I downloaded your repository, adjusted cmake to get the aura, shaders... and ran it cleanly without any modifications.
I only activated the features indicated in the repository. Remember that I'm using Linux!

**Comment by kokekanon** [comment]
your problem is **TFS** in linux / cmaker .

i know nothing about linux and cmaker. i can't help you.
windows compilation VS community 2022 works with this.
```
g_game.enableFeature(GameWingsAurasEffectsShader)
g_game.enableFeature(GameFormatCreatureName)
g_game.enableFeature(GameCreatureShader)
g_game.enableFeature(GameCreatureAttachedEffect) 
g_game.enableFeature(GameItemShader)
```

the problem is NOT in **otc**, next time talk on the discord group or otland . don't create issue for **OTC** , when the problem is in tfs.

the only otc issue i see is 


# 1) `ERROR: invalid thing type client id 0 in category 4`


to fix that we need to delete this

https://github.com/mehah/otclient/blob/main/modules/game_outfit/outfit.lua#L99-L101

https://github.com/mehah/otclient/blob/main/modules/game_outfit/outfit.lua#L1059-L1061

# 2) size UICreature:
![image](https://github.com/user-attachments/assets/7c9e74a5-56ac-4a8c-b091-5845b28903d1)

to fix that we need to delete this https://github.com/mehah/otclient/blob/main/modules/game_outfit/outfit.lua#L849

**Comment by regizfilho** [comment]
> your problem is **TFS** in linux / cmaker .
> 
> i know nothing about linux and cmaker. i can't help you. windows compilation VS community 2022 works with this.
> 
> ```
> g_game.enableFeature(GameWingsAurasEffectsShader)
> g_game.enableFeature(GameFormatCreatureName)
> g_game.enableFeature(GameCreatureShader)
> g_game.enableFeature(GameCreatureAttachedEffect) 
> g_game.enableFeature(GameItemShader)
> ```
> 
> the problem is NOT in **otc**, next time talk on the discord group or otland . don't create issue for **OTC** , when the problem is in tfs.
> 
> the only otc issue i see is
> 
> # 1) `ERROR: invalid thing type client id 0 in category 4`
> to fix that we need to delete this
> 
> https://github.com/mehah/otclient/blob/main/modules/game_outfit/outfit.lua#L99-L101
> 
> https://github.com/mehah/otclient/blob/main/modules/game_outfit/outfit.lua#L1059-L1061
> 
> # 2) size UICreature:
> ![image](https://private-user-images.githubusercontent.com/114332266/368588093-7c9e74a5-56ac-4a8c-b091-5845b28903d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2NzA5NzIsIm5iZiI6MTcyNjY3MDY3MiwicGF0aCI6Ii8xMTQzMzIyNjYvMzY4NTg4MDkzLTdjOWU3NGE1LTU2YWMtNGE4Yy1iMDkxLTU4NDViMjg5MDNkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQxNDQ0MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzM5NmZjN2QwNTJkMzllODJmY2Q5MDA2MjFkNDc4MmEzMDNlNjE1YmNmNDllZWJjYTIzNWUxY2QyMmNhZmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0rtNc3AtAXftRr9j2TzKu5OTYClAayZDRL2UEb9aml0)
> 
> to fix that we need to delete this https://github.com/mehah/otclient/blob/main/modules/game_outfit/outfit.lua#L849

To activate the attached resources, a specific customization is made for the otc, clearly this is the best place to ask, I see no problem coming here. The point is that you don't have an answer to this, I investigated through other means, thank you for your support.
